title: Possible Registry Key Modification to Change Credential Security Support Provider Settings (via registry_event )
status: stable
description: This rule detects the adversaries that attempt to modify associated registry key by changing protection level of CredSSP components which allows the threat actors to fall back  to the insecure versions. With the help of this changing the remote server will be exposed to attacks via services using CredSSP will accept unpatched client. 
author: Emre Ay
references:
- https://www.welivesecurity.com/en/eset-research/scarabs-colon-izing-vulnerable-servers/
- https://admx.help/?Category=Windows_10_2016&Policy=Microsoft.Policies.CredentialsSSP::AllowEncryptionOracle
- https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1112/T1112.md#atomic-test-63---scarab-ransomware-defense-evasion-activities
logsource:
  product: windows
  category: registry_event
detection:
  selection:
    TargetObject|endswith:
    - '\CurrentVersion\Policies\System\CredSSP\Parameters\AllowEncryptionOracle'
    Details:
    - 'DWORD (0x00000002)'
  condition: selection
falsepositives:
- Unlikely
tags:
- attack.defense_evasion
- attack.t1112
level: medium
