title: Possible Commands Executed on MacOs to Get Information about Applications (via process_creation)
status: stable
description: This rule detects the adversaries that attempt to delete Time to Live log files on MacOS environment using built-in log utility.
author: Emre Ay
references:
- https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1070.002/T1070.002.md#atomic-test-2---delete-log-files-using-built-in-log-utility
logsource:
  product: macos
  category: process_creation
detection:
  selection:
    CommandLine|contains|all:
    - 'log'
    - 'erase'
    - '--ttl'
  condition: selection
falsepositives:
- Unlikely
level: high
tags:
- attack.defense_evasion
- attack.t1070.002
