title: Possible Persistence Activity on Azure Environment by Creating Automation Runbook (via ps_script)
id: 0c32c3d8-f1e9-45c1-bfed-ebc093e7f10a
status: stable
description:This rule detects the suspicious automationrunbook creation to ensure persistence on compromised azure environment. The threat actors can use this method to maintain persistence and execute their malicious code.
author: Emre Ay
references:
- https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1078.004/T1078.004.md#atomic-test-2---azure-persistence-automation-runbook-created-or-modified
logsource:
  product: windows
  category: ps_script
detection:
  selection:
    ScriptBlockText|contains|all :
    - 'New-AzAutomationRunbook'
    - '-Name'
    - '-ResourceGroupName'
  condition: selection
falsepositives:
- The possible admin activity
level: low
tags:
- attack.persistence
- attack.defense_evasion
- attack.t1078.004
