title: Possible Registry Key Modification to Disable Windows Defender Application Control (via  registry_event )
status: stable
description: This rule detects the suspicious modification of associated registry key to disable windows defender application control code integrity policy which allows the threat actors to run malicious code on victim machine.
author: Emre Ay
references:
- https://admx.help/?Category=Windows_10_2016&Policy=Microsoft.Windows.DeviceGuard::ConfigCIPolicy
logsource:
  product: windows
  category: registry_event
detection:
  selection:
    TargetObject|endswith:
    - '\Microsoft\Windows\DeviceGuard\DeployConfigCIPolicy'
    Details:
    - 'DWORD (0x00000000)'
  condition: selection
falsepositives:
- Unlikely
tags:
- attack.defense_evasion
- attack.t1112
level: medium
