title: Suspicious Discovery Activity to Get System's Region and Language Settings (via ps_script)
status: stable
description:This rule detects the suspicious powershell command which allows to discover information about the current culture settings such as the keyboard layout and display format of items on compromised system. The threat actors can use this technique to prepare their further activities.
author: Emre Ay
references:
- https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1082/T1082.md#atomic-test-37---identify-system-locale-and-regional-settings-with-powershell
logsource:
  product: windows
  category: ps_script
detection:
  selection:
    ScriptBlockText|contains|all :
    - 'Get-Culture'
    - 'Format-List'
  condition: selection
falsepositives:
- unlikely
level: medium
tags:
- attack.discovery
- attack.t1082
- attack.execution
- attack.t1059.001
