title: Suspicious Command Execution to Delete Amazon Guardduty Intelligent Threat Detection Configuration (via process_creation)
id: 0be5ea86-87bd-4238-84c9-8b4dc9ebe2a9
status: stable
description: This rule detects the command execution that attempt to disable/delete amazon guardduty configuration such as intelligent threat detection service in AWS.  
author: Emre Ay
references:
- https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1562.001/T1562.001.md#atomic-test-46---aws---guardduty-suspension-or-deletion
logsource:
  product: linux
  category: process_creation
detection:
  selection:
    CommandLine|contains|all:
    - 'guardduty'
    - 'delete-detector'
    - '--detector-id'
  condition: selection
falsepositives:
- Unlikely
level: high
tags:
- attack.defense_evasion
- attack.t1562.001
