title: Suspicious Command Execution to Get Windows Firewall Profiles and Settings (via ps_script)
status: stable
description:This rule detects the suspicious powershell command that aim to get windows firewall profiles and settings from the compromised host. 
references:
- https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1518.001/T1518.001.md#atomic-test-10---security-software-discovery---windows-firewall-enumeration
- https://learn.microsoft.com/en-us/powershell/module/netsecurity/get-netfirewallprofile?view=windowsserver2022-ps
- https://learn.microsoft.com/en-us/powershell/module/netsecurity/get-netfirewallsetting?view=windowsserver2022-ps
logsource:
  product: windows
  category: ps_script
detection:
  selection:
    ScriptBlockText|contains :
    - 'Get-NetFirewallProfile'
    - 'Get-NetFirewallSetting'
  condition: selection
falsepositives:
- The possible admin activity
level: medium
tags:
- attack.discovery
- attack.t1518.001
- attack.execution
- attack.t1059.001
